### ISSUE TITLE
yeoman, grunt, bower --> web components e.g. with Google's Polymer

### ISSUE THREAD

**Issue by markusgattol** [radiegtya/meteoris#18]
why not shift this scaffolding into a yeoman generator such as https://github.com/Pent/generator-meteor ? This way one could use all the benefits of grunt, yo, bower as well. That makes especially sense on the upcoming web components revolution e.g. if one would use Meteor + Polymer for example.

**Comment by radiegtya** [comment]
This is a good idea but it will make meteoris to be reworked almost every code.
So anyone willing to help are welcome.

**Comment by ssteinerx** [comment]
I think using a more template-like syntax for the boilerplate would be helpful (right now it is just a search for "replace"), but I agree with @MercedesAMG1 -- overcomplicating this simple tool with grunt et al. would add an unnecessary level of complexity to a very simple tool.

**Comment by radiegtya** [comment]
I'll close this for now.
