### ISSUE TITLE
too small max length for field name

### ISSUE THREAD

**Issue by anderson916** [radiegtya/meteoris#26]
client/mugen/_form.js:
  102              var nameMatch = name.match(/^[a-z0-9A-Z_]{3,15}$/);

15 is too small for max field name length. Please increase to at least 30.

**Comment by radiegtya** [comment]
Cool @anderson916 

I'll fix that, and mark it as bug.
Sorry for that dump mistake.

**Comment by radiegtya** [comment]
fixed at the latest meteoris.

just reopen if you still find any bug.
Thanks
