### ISSUE TITLE
camel hump collection name support

### ISSUE THREAD

**Issue by anderson916** [radiegtya/meteoris#27]
mugen just changes all collection names to lower case, but sometimes I'd like to use DeviceParameters as the collection name.

Please consider to support this. Thanks.

**Comment by radiegtya** [comment]
Do you mean that You want a collection named "DeviceParameters"?

Btw I'll try to support this. 

Thanks @anderson916

**Comment by radiegtya** [comment]
@anderson916: check the latest update of meteoris 0.9.6.
I have add camel hump collection name support for meteoris.

Thanks
