### ISSUE TITLE
Regenerating a collection adds another identical entry in "collections" section of roles

### ISSUE THREAD

**Issue by ssteinerx** [radiegtya/meteoris#33]
Even though mugen isn't (yet) saving collection information, it seems to be keeping a list of created collections.

If you recreate a collection, that list contains multiple copies of the same collection name.

Steve

**Comment by radiegtya** [comment]
I'll make the mugen role collection name field being unique asap

**Comment by radiegtya** [comment]
please check this current version, if you find any bug just reopen.

Thanks
