### ISSUE TITLE
Collections shouldn't be allowed to be created with no logged in user

### ISSUE THREAD

**Issue by ssteinerx** [radiegtya/meteoris#34]
When creating collections without being logged in, even admin is denied access to the collection.

IOW, if you create a collection when not logged in, the collection is completely inaccessible.

**Comment by ssteinerx** [comment]
Actually, even logged in as admin, creating a new collection leaves it completely inaccessible, even still logged in as admin.  This happens in both flipped and master branches.

**Comment by radiegtya** [comment]
hehe, maybe I should make a documentation about this. 
Actually you can easily turn on/off mugen using lib/applications/meteoris/configs/config.js.

just set the variable isActivateMugen to false and You are ready for production.

**Comment by ssteinerx** [comment]
I don't understand why you closed this if it's not fixed or documented.

**Comment by radiegtya** [comment]
I had made the documentation in video tutorial about meteoris (complete 7 series), but I hadn't time to uploaded it yet to youtube. And ofc I'll serve the doc too ASAP.

Thanks
