### ISSUE TITLE
how to use mutiple modules or sub system?

### ISSUE THREAD

**Issue by yuomtheara** [radiegtya/meteoris#39]
I would like to use multiple `modules/sub system` like:
```
loan/
..............
saving/
.............
```
How to custom structure?

**Comment by radiegtya** [comment]
You can easily doing that. Btw have you really have deep understanding about structuring meteor?

**Comment by yuomtheara** [comment]
Thanks, I come from Laravel PHP framework, so it is new.

**Comment by radiegtya** [comment]
It's ok,  meteoris are also inspired from laravel, although the biggest code base style are from yii. Just keep try to use meteor and it will be easy (structuring etc)
