### ISSUE TITLE
request to use pagination and show page on list view?

### ISSUE THREAD

**Issue by yuomtheara** [radiegtya/meteoris#40]
I have many of recoreds on list view.
how to use pagination and show page option like datatable?

**Comment by radiegtya** [comment]
In realtime apps, pagination like on datatable are not good. (You can see the reason at discover meteor book)
Load more style will be better.

**Comment by yuomtheara** [comment]
thanks for your reply.

**Comment by radiegtya** [comment]
you r welcome, and hopes it clear
