### ISSUE TITLE
xediting and css hover effects

### ISSUE THREAD

**Issue by AirJordan6811** [radiegtya/meteoris#42]
Are there any problems when using xeditable in the grid? And how can I generate with CSS hover effects in the grid row? Thx for helping!

**Comment by radiegtya** [comment]
I think the meteoris UX designer @vLo-Love can answer this. Please wait for his answer :)

**Comment by AirJordan6811** [comment]
@radiegtya Thx for the answer. I´m added in the gridView.css:

.table tbody .modelRow td:hover{
    background-color: gray;
}

and added in the collection index.html the <tr> with the class="modelRow". So it works only in the field but not in the whole row.

**Comment by AirJordan6811** [comment]
I have the solution! Added in gridView.css:

.table tbody .modelRow:hover{
    background-color: #f5f5f5;
}

And added in the collection index.html the "tr" with the class="modelRow". So it works. Now I'm looking for a solution for the integration xeditable. Perhaps @vLo-Love have some.

**Comment by radiegtya** [comment]
if you want to use x-editable, just use this extension:

https://atmospherejs.com/natestrauser/x-editable-bootstrap

I am not testing it yet, but maybe it will be the solution

**Comment by AirJordan6811** [comment]
Ok thx @radiegtya ! Meteoris is using bootstrap3?

**Comment by radiegtya** [comment]
yes bootstrap 3. I think I can close this. reopen if there is another question,
