### ISSUE TITLE
Collections Error

### ISSUE THREAD

**Issue by marcojferreirac** [radiegtya/meteoris#52]
Hi, i've been using Meteoris and today i encountered a big problem.

I exported my database to mine, instead of the local one i've been using (localhost:3001) and now, the collections that i've created with the Crudss Generator stopped working. Even "Jobs" and "Employees".

When i try to access them, redirects me to 403 forbidden.

All the roles are in the database but those collections aren't. I can login, users collection is working, but i can't even go to users/profile when logged in as admin. I get redirected to page 403 forbidden.

Any ideas on why this is happening? Shouldn't the collections be created the same way?

thanks a lot

**Comment by radiegtya** [comment]
try to also restore this collections:

- mugenRoleCollections
- mugenRoleGroups
- mugenRoleActions

**Comment by marcojferreirac** [comment]
i've solved the issued, thanks. that was the problem, i haven't created the collections in the server side.

Still getting an error with the new mongodb, i have to run export before running meteor for it to work...

Just one more question, if you can help me with it... is it possible to save a pdf file in one of the fields of a collection? 

thanks a lot. my first issue is solved!

**Comment by radiegtya** [comment]
very possible, just use upload example and you r done
