### ISSUE TITLE
How do you relate two collections meteoris using code generator?

### ISSUE THREAD

**Issue by Ajaxsoap** [radiegtya/meteoris#74]
Hi,
I have a scenario, I have two collections. 
enrollments collection
claims collection

I have enrollees list in enrollments collection. 
How do I pass a certain fields from enrollments collection to claims collection with additional fields from the client? 

Example
<strong>Enrollments collection</strong>
<table>
<thead><tr><th>Name</th><th>Birthdate</th><th>Birthdate</th><th></th></tr></thead>
<tbody>
<tr>
<td>John</td>
<td>02/02/1990</td>
<td>Single</td>
<td>Claim me!</td>
</tr>
<tr>
<td>Peter</td>
<td>02/02/1980</td>
<td>Married</td>
<td>Claim me!</td>
</tr>
</tbody>
</table>

Let say i placed a claims button (Claim me!) per enrollee in the list, then if I click it, it will route me to add claims, the fields from that particular enrollee will be carried over plus additional fields(amount,dateofClaims), then click submit.<br>
<strong>Claims collection</strong>
<table>
<thead><tr><th>Name</th><th>Birthdate</th><th>Birthdate</th><th>Amount</th><th>Date Claimed</th></tr></thead>
<tbody>
<tr>
<td>John</td>
<td>02/02/1990</td>
<td>Single</td>
<td>$500</td>
<td>06/06/2015</td>
</tr>
</tbody>
</table>

How do i use the generator for this kind of scenario?

Thanks.

**Comment by radiegtya** [comment]
@Ajaxsoap 
Simply you can easily make enrollments collection with field:
- name
- birthDate
- status
- amount
- claimedDate

or if you want relational

enrollments collection:
- name
- birthDate
- status
- claimId (name), Claims (Relation), claim (relationKey)

claims collection:
- amount
- date (this is not necessary because meteoris out of the box give you field called "createdAt" and "updatedAt"

**Comment by Ajaxsoap** [comment]
Thanks @radiegtya! 

However, I didn't get the output that I desired, the output that I want to achieve is passing a data from one collection to another. The approach that you suggested is simply putting a claims on enrollees but it didn't make sense if the enrollee is not yet claiming. The claim ID is supposedly appear <strong>after</strong> the enrollee claimed. Maybe, I have to figure this out by myself. 

Thanks again and more power @radiegtya !

**Comment by radiegtya** [comment]
use the relational one then.

I think this is simply just logic, not much related to meteoris it self. I am closing this for now, feels free to reopen if you have another question.
